[package]
name = "athlete_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = "23.0.2"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
